# Generated by Django 6.0.4 on 2026-10-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0009_rename_budget_budget_limit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactions",
            name="category",
            field=models.CharField(
                choices=[
                    ("Salary", "Salary"),
                    ("Food", "Food"),
                    ("Groceries", "Groceries"),
                    ("Travel", "Travel"),
                    ("Shopping", "Shopping"),
                    ("Bills", "Bills"),
                    ("Entertainment", "Entertainment"),
                    ("Other", "Other"),
                ],
                default="Salary",
                max_length=100,
            ),
        ),
    ]
