# Generated by Django 6.0.4 on 2026-09-05 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialHealthScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('savings_score', models.PositiveSmallIntegerField()),
                ('expense_score', models.PositiveSmallIntegerField()),
                ('budget_score', models.PositiveSmallIntegerField()),
                ('overspending_score', models.PositiveSmallIntegerField()),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-calculated_at'],
                'indexes': [models.Index(fields=['user', 'calculated_at'], name='financial_a_user_id_9b63ab_idx')],
            },
        ),
        migrations.CreateModel(
            name='FinancialInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('message', models.TextField()),
                ('insight_type', models.CharField(choices=[('positive', 'Positive'), ('warning', 'Warning'), ('info', 'Information')], default='info', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='financial_a_user_id_76035e_idx')],
            },
        ),
    ]
