# Generated by Django 6.0.4 on 2026-09-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialinsight',
            name='data_signature',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='financialinsight',
            name='source',
            field=models.CharField(default='rule', max_length=10),
        ),
    ]
